---
- name: Create User
  uri:
    url: '{{ atlassian.url }}/rest/api/2/user'
    method: POST
    user: '{{ atlassian.username }}'
    password: '{{ atlassian.password }}'
    force_basic_auth: yes
    status_code: 201
    body_format: json
    body:
      name: "{ atlassian_user.email.split(\"@\") | first }}"
      emailAddress: "{{ atlassian_user.email }}"
      displayName: "{{ atlassian_user.firstname }} {{ atlassian_user.lastname }}"
      notification: true
    return_content: yes
  register: user_data
  when: 
    - atlassian_user.state|default('present') == 'present'